// <auto-generated />
namespace WEB_TRUONG_SP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateBanner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateBanner));
        
        string IMigrationMetadata.Id
        {
            get { return "202407290917504_updateBanner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
