// <auto-generated />
namespace WEB_TRUONG_SP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class adddata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddata));
        
        string IMigrationMetadata.Id
        {
            get { return "202407110137280_add-data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
